services:
  postgres:
    container_name: user_service_postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${CRM_USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CRM_USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CRM_USER_POSTGRES_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${CRM_USER_POSTGRES_PORT}:${CRM_USER_POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  user_service:
    container_name: user_service
    image: crm-user:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${CRM_USER_PORT}:${CRM_USER_PORT}
    environment:
      PORT: ${CRM_USER_PORT}

      DB_USER: ${CRM_USER_POSTGRES_USER}
      DB_PASSWORD: ${CRM_USER_POSTGRES_PASSWORD}
      DB_NAME: ${CRM_USER_POSTGRES_NAME}
      DB_PORT: ${CRM_USER_POSTGRES_PORT}
      DB_HOST: ${CRM_USER_POSTGRES_HOST}

volumes:
  postgres_data:
