// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * User Service API
 *
 * API of User microservice
 *
 * API version: 0.0.1
 */

package userApi




type CreateUserRequest struct {

	Permissions int32 `json:"permissions"`

	Type string `json:"type"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Email string `json:"email"`

	Phone string `json:"phone,omitempty"`

	TgName string `json:"tgName,omitempty"`

	Status UserStatus `json:"status"`
}

// AssertCreateUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateUserRequestRequired(obj CreateUserRequest) error {
	elements := map[string]interface{}{
		"permissions": obj.Permissions,
		"type": obj.Type,
		"firstName": obj.FirstName,
		"lastName": obj.LastName,
		"email": obj.Email,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateUserRequestConstraints(obj CreateUserRequest) error {
	return nil
}
