// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * User Service API
 *
 * API of User microservice
 *
 * API version: 0.0.1
 */

package userApi




type User struct {

	Id string `json:"id,omitempty"`

	Permissions int32 `json:"permissions,omitempty"`

	Type string `json:"type,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	TgName string `json:"tgName,omitempty"`

	Status UserStatus `json:"status,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`
}

// AssertUserRequired checks if the required fields are not zero-ed
func AssertUserRequired(obj User) error {
	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
